name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
       submodules: true
    - name: Initialize Xcode Project
      run: swift package generate-xcodeproj
    - name: Build
      run: xcodebuild build -sdk iphoneos -scheme 'Incito-Package'
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'Incito-Package'
